### ISSUE TITLE
EelHelpers with ...$param not working

### ISSUE THREAD

**Issue by Benjamin-K** [sjsone/vscode-neos-fusion-lsp#4]
EelHelper methods, that use `...$params` parameters often show a `Too many arguments provided` error message (which is wrong). Therefore, the parser of the method parameters should add the last parameter several times, if the name starts with three dots (`...`), see https://github.com/sjsone/vscode-neos-fusion-lsp/blob/main/server/src/neos/NeosPackageNamespace.ts#L130.

This happens for example when using `AtomicFusion.classNames`.

**Comment by sjsone** [comment]
Many thanks for bringing this issue to my attention! 
I'm glad to inform you that it is fixed in the Pre-Release Version 0.2.3

While the first variadic parameter displays the complete inlay hint, each subsequent parameter only shows its offset: 
<img width="747" alt="Screenshot 2023-04-19 at 21 37 08" src="https://user-images.githubusercontent.com/87149727/233196382-0db0f586-f999-46fb-8cc7-f3343fd1c63a.png">

**Comment by Benjamin-K** [comment]
Wow, that was fast, thank you!
