### ISSUE TITLE
Missing NodeType Definition on abstract prototypes

### ISSUE THREAD

**Issue by Benjamin-K** [sjsone/vscode-neos-fusion-lsp#7]
If one creates an abstract prototype that inherits from `Neos.Neos:ContentComponent` and will be used by other prototypes, the language server will search a NodeType-Definition for that prototype, that doesn't exist, because it will be used by other prototypes that have an existing NodeType Definition.

Example:
<img width="820" alt="image" src="https://github.com/sjsone/vscode-neos-fusion-lsp/assets/3098031/b5287f6d-04d0-40ce-bdc0-071b99ad9dcb">

And then some other prototypes (that have a NodeType Definition), that inherit from the abstract prototype. For example:
```
prototype(Package.Namespace:Molecule.TeamSectionA) < prototype(Package.Namespace:Abstract.Molecule.TeamSection)
```

For now this can be "fixed" by adding `// @fusion-ignore` in the line above the abstract prototype, but i would prefer an automatic check for other nodetypes. 

Is such an implementation possible?

**Comment by sjsone** [comment]
Thank you very much for bringing this up!

### Problem

Yes, it would be possible, but it would introduce guessing into the Diagnostics decision which could guess it wrong. 

Take the following example:

We have an ImageSlider which is a ContentComponent:
```javascript
prototype(Vendor.Website:Molecule.ImageSlider) < prototype(Neos.Neos:ContentComponent)
```

And a HeroImageSlider which extends the ImageSlider:
```javascript
prototype(Vendor.Website:Molecule.HeroImageSlider) < prototype(Vendor.Website:Molecule.ImageSlider)
```

Therefore the same structure of inheritance as in your example. But in this case there has to be a NodeType-Definition for the "middle" ContentComponent. We _could guess_  and treat the prototype in your example different because there is `Abstract` in its name, but that would be guessing. This would lead to false negatives. There is no _language defined_ way of declaring a prototype as abstract. 

So thats not the way to go in my opinion. 

### Solution

#### Ignore
`Neos.Neos:ContentComponent` can already be explicitly ignored by adding them to the `Ignore Node Types` Setting:   
<img width="891" alt="Screenshot 2023-09-29 at 19 27 38" src="https://github.com/sjsone/vscode-neos-fusion-lsp/assets/87149727/fdb0fe3f-0489-4b35-9685-ffb59c67a232">

#### NodeType
As there is no way to declare a prototype as abstract or non-directly-renderable, the only way is to create a NodeType file which just declares the NodeType as abstract. This also should keep the inheritance of prototypes and NodeType-Configuration in sync. 

If the language/NEOS defines something that resembles abstract prototypes (maybe `Neos.Fusion:Component` without a `renderer`) this can be solved in a better way.  

### Next Steps
I know these solutions sound a bit sarcastic but I think the *real* solution is to improve the UI to streamline these interactions. 

So I propose to add two new Quick-Actions:
- add a NodeType to the  `Ignore Node Types` Setting
- create an abstract NodeType file based on a user changeable Detection-RegEx. So by default it would detect the `Abstract` in its name and create a simple file. Maybe even without changing tabs to not interrupt the user flow. 

These Quick-Actions make false-positives (your example) user-resolvable. In contrast to the solution above which would introduce false-negatives.

Hopefully that is a satisfactory answer. If not I am happy to discuss other ideas!

**Comment by Benjamin-K** [comment]
Thank you very much for such a detailled answer. I think creating NodeType-Definitions that just declare the NodeType as abstract is the best solution for now. 

To add one more posible option that needs to be added to the language server:
Better than just using `// @fusion-ignore` would be the option to only ignore some parts, sth like `// @fusion-ignore missing-nodetype`. But for now i'm fine with this and you can close this issue if you want.

**Comment by sjsone** [comment]
There is something like `@fusion-ignore-missing-node-type-decleration` planned because the better option is almost every time to just create a NodeType file. 

The whole `@fusion-ignore` will get an overhaul when the language server is in version 1.0

**Comment by sjsone** [comment]
The change is now live as pre-release 0.3.7
